### ISSUE TITLE
[Matrix::Client] Could not find Matrix::Response

### ISSUE THREAD

**Issue by dontlaugh** [matiaslina/Matrix-Client#19]
I tried to install with 

```
zef install Matrix::Client
```

Eventually I got this error:

```
[Matrix::Client] Could not find Matrix::Response
```

I'm new to Raku, so I'm unsure what's going on. :sweat_smile:

**Comment by matiaslina** [comment]
Hi @dontlaugh! Thanks for the report :)

> Eventually I got this error:

Did you got that error during the installation of `Matrix::Client` or by running some script?

I've tried to uninstall and install again `Matrix::Client` from zef and didn't get an error.

```
[~]
% zef install Matrix::Client
===> Searching for: Matrix::Client
===> Testing: Matrix::Client:ver<0.6.1>
===> Testing [OK] for Matrix::Client:ver<0.6.1>
===> Installing: Matrix::Client:ver<0.6.1>
[~]
% raku                                                                                                       
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.11.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2020.11.

To exit type 'exit' or '^D'
> use Matrix::Client;
Nil
> use Matrix::Client::Room;
Nil
> use Matrix::Response;
Nil
```

**Comment by matiaslina** [comment]
Closing it for now. Feel free to reopen this issue if you have the error again.
